---
version: "2.4"

services:
  db:
    container_name: mongo
    image: ${MONGO_IMAGE:-mongo:4.0}
    restart: always
    volumes:
      - /tmp/mongodb_unifi/mongodb:/data/db

  unifi:
    container_name: unifi
    image: ${UNIFI_IMAGE:-unifi:devel}
    volumes:
      - /tmp/mongodb_unifi/var/lib/unifi:/opt/app/unifi/data
    ports:
      - 3478:3478/udp
      - 8080:8080
      - 8443:8443
    environment:
      - UNIFI_DB_HOST=mongo
      - UNIFI_DB_NAME=ace
      - WAITFOR_TIMEOUT=60
